name: Reclip

options:
  bundleIdPrefix: com.reclip
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: ""  # 填入你的 Team ID
    CODE_SIGN_IDENTITY: "-"  # 本地開發使用 ad-hoc 簽名
    CODE_SIGN_STYLE: Manual
    ENABLE_HARDENED_RUNTIME: true

packages:
  ReclipKit:
    path: ./ReclipKit

targets:
  Reclip:
    type: application
    platform: macOS
    sources:
      - path: Reclip
        excludes:
          - "*.entitlements"
    dependencies:
      - package: ReclipKit
        product: ReclipCore
      - package: ReclipKit
        product: ReclipASR
      - package: ReclipKit
        product: ReclipLLM
      - package: ReclipKit
        product: ReclipUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reclip.app
        PRODUCT_NAME: Reclip
        INFOPLIST_FILE: Reclip/Info.plist
        CODE_SIGN_ENTITLEMENTS: Reclip/Reclip.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: Reclip/Reclip.entitlements

schemes:
  Reclip:
    build:
      targets:
        Reclip: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug": "1"
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
